version: '3.5'

services:
  db-to-do-list:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql
    env_file:
      - ./config/db.env
    ports:
      - "5432:5432"
    networks:
      - backend
  app:
    build: .
    restart: always
    depends_on:
      - db-to-do-list
    env_file:
      - ./config/app.env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    networks:
      - backend

volumes:
  db_data: {}
networks:
  backend:
    driver: bridge